baseURL: /
languageCode: en-us
theme: smigle
title: Malware Technology
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 3
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 4
params:
  abbrDateFmt: "Jan 2"
  author: "Nicholas McKinney"
  brandIconFile: "images/brandIcon.svg"
  dateFmt: "2006-01-02"
#  customStylesheets: # Use to override theme styles, like logo size
#    - "css/custom.css"
  social:
    - name: GitHub
      url: https://github.com/nicholasmckinney
  subtitle: "Personal Journal on Defensive Cybersecurity, DevOps, and anything that comes to mind"
